name: CI
on: [push]

jobs:
  first-build:
       runs-on: ubuntu-latest
       steps:
          - name: Checkout Code
            uses: actions/checkout@v4

          - name: Echo
            run: |
               echo "hello world"
               sudo apt update
               echo "packages updated successfully"
